### ISSUE TITLE
Page for "JavaScript API" Not Existed

### ISSUE THREAD

**Issue by vietnv2707** [liveoak-io/liveoak#452]
Cannot found page of JavaScript API is refered in link http://liveoak.io/docs/advanced/scripting/:
http://liveoak.io/docs/reference/scripting/javascript/out/index.html

**Comment by kenfinnigan** [comment]
Sorry for the delay, this should now be fixed.

Links from the Advanced Scripting page now correctly go to http://liveoak.io/docs/advanced/javascript_api/index.html
